name: publish to pypi

run-name: publish to pypi

on:
  workflow_dispatch:
    inputs:
      python_version:
        description: "Python version to use (default: 3.12)"
        required: false
        default: "3.12"

jobs:
  wait-for-approval:
    uses: .github/workflows/manual_approver.yaml

  publish-to-pypi:
    needs: wait-for-approval
    uses: .github/workflows/poetry_publish.yaml
    with:
      python_version: ${{ inputs.python_version || '3.12' }}
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
